/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;

/**
 *
 * @author Andrey
 */
public class Pastilla extends javax.swing.JFrame {

    /**
     * Creates new form Pastilla
     */
    public Pastilla() {
        initComponents();
        A0.setText("A0");
A0.setOpaque(true);
A0.setBackground(Color.white);
A1.setText("A1");
A1.setOpaque(true);
A1.setBackground(Color.white);
A2.setText("A2");
A2.setOpaque(true);
A2.setBackground(Color.white);
A3.setText("A3");
A3.setOpaque(true);
A3.setBackground(Color.white);
A4.setText("A4");
A4.setOpaque(true);
A4.setBackground(Color.white);
A5.setText("A5");
A5.setOpaque(true);
A5.setBackground(Color.white);
A6.setText("A6");
A6.setOpaque(true);
A6.setBackground(Color.white);
A7.setText("A7");
A7.setOpaque(true);
A7.setBackground(Color.white);
A8.setText("A8");
A8.setOpaque(true);
A8.setBackground(Color.white);
A9.setText("A9");
A9.setOpaque(true);
A9.setBackground(Color.white);
A10.setText("A10");
A10.setOpaque(true);
A10.setBackground(Color.white);
A11.setText("A11");
A11.setOpaque(true);
A11.setBackground(Color.white);
A12.setText("A12");
A12.setOpaque(true);
A12.setBackground(Color.white);
A13.setText("A13");
A13.setOpaque(true);
A13.setBackground(Color.white);
A14.setText("A14");
A14.setOpaque(true);
A14.setBackground(Color.white);
A15.setText("A15");
A15.setOpaque(true);
A15.setBackground(Color.white);
D0.setText("D0");
D0.setOpaque(true);
D0.setBackground(Color.white);
D1.setText("D1");
D1.setOpaque(true);
D1.setBackground(Color.white);
D2.setText("D2");
D2.setOpaque(true);
D2.setBackground(Color.white);
D3.setText("D3");
D3.setOpaque(true);
D3.setBackground(Color.white);
D4.setText("D4");
D4.setOpaque(true);
D4.setBackground(Color.white);
D5.setText("D5");
D5.setOpaque(true);
D5.setBackground(Color.white);
D6.setText("D6");
D6.setOpaque(true);
D6.setBackground(Color.white);
D7.setText("D7");
D7.setOpaque(true);
D7.setBackground(Color.white);
M1.setText("M1");
M1.setOpaque(true);
M1.setBackground(Color.white);
MREQ.setText("MREQ");
MREQ.setOpaque(true);
MREQ.setBackground(Color.white);
IORQ.setText("IORQ");
IORQ.setOpaque(true);
IORQ.setBackground(Color.white);
RD.setText("RD");
RD.setOpaque(true);
RD.setBackground(Color.white);
WR.setText("WR");
WR.setOpaque(true);
WR.setBackground(Color.white);
RFSH.setText("RFSH");
RFSH.setOpaque(true);
RFSH.setBackground(Color.white);
HALT.setText("HALT");
HALT.setOpaque(true);
HALT.setBackground(Color.white);
WAIT.setText("WAIT");
WAIT.setOpaque(true);
WAIT.setBackground(Color.white);
INT.setText("INT");
INT.setOpaque(true);
INT.setBackground(Color.white);
MMI.setText("MMI");
MMI.setOpaque(true);
MMI.setBackground(Color.white);
RESET.setText("RESET");
RESET.setOpaque(true);
RESET.setBackground(Color.white);
BUSRQ.setText("BUSRQ");
BUSRQ.setOpaque(true);
BUSRQ.setBackground(Color.white);
GND.setText("GND");
GND.setOpaque(true);
GND.setBackground(Color.GRAY);
BUSACK.setText("BUSACK");
BUSACK.setOpaque(true);
BUSACK.setBackground(Color.white);
V5.setText("+5V");
V5.setOpaque(true);
V5.setBackground(Color.red);
CLK.setText("CLK");
CLK.setOpaque(true);
CLK.setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    /*
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        A0 = new javax.swing.JLabel();
        A1 = new javax.swing.JLabel();
        A2 = new javax.swing.JLabel();
        A3 = new javax.swing.JLabel();
        A4 = new javax.swing.JLabel();
        A5 = new javax.swing.JLabel();
        A6 = new javax.swing.JLabel();
        A7 = new javax.swing.JLabel();
        A8 = new javax.swing.JLabel();
        A9 = new javax.swing.JLabel();
        A10 = new javax.swing.JLabel();
        A11 = new javax.swing.JLabel();
        A12 = new javax.swing.JLabel();
        A13 = new javax.swing.JLabel();
        A14 = new javax.swing.JLabel();
        A15 = new javax.swing.JLabel();
        D0 = new javax.swing.JLabel();
        D1 = new javax.swing.JLabel();
        D2 = new javax.swing.JLabel();
        D3 = new javax.swing.JLabel();
        D4 = new javax.swing.JLabel();
        D5 = new javax.swing.JLabel();
        D6 = new javax.swing.JLabel();
        D7 = new javax.swing.JLabel();
        M1 = new javax.swing.JLabel();
        MREQ = new javax.swing.JLabel();
        IORQ = new javax.swing.JLabel();
        RD = new javax.swing.JLabel();
        WR = new javax.swing.JLabel();
        RFSH = new javax.swing.JLabel();
        HALT = new javax.swing.JLabel();
        WAIT = new javax.swing.JLabel();
        INT = new javax.swing.JLabel();
        MMI = new javax.swing.JLabel();
        RESET = new javax.swing.JLabel();
        BUSRQ = new javax.swing.JLabel();
        GND = new javax.swing.JLabel();
        BUSACK = new javax.swing.JLabel();
        V5 = new javax.swing.JLabel();
        CLK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Z80");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel1)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        A0.setText("A0");

        A1.setText("A1");

        A2.setText("A2");

        A3.setText("A3");

        A4.setText("A4");

        A5.setText("A5");

        A6.setText("A6");

        A7.setText("A7");

        A8.setText("A8");

        A9.setText("A9");

        A10.setText("A10");

        A11.setText("A11");

        A12.setText("A12");

        A13.setText("A13");

        A14.setText("A14");

        A15.setText("A15");

        D0.setText("D0");

        D1.setText("D1");

        D2.setText("D2");

        D3.setText("D3");

        D4.setText("D4");

        D5.setText("D5");

        D6.setText("D6");

        D7.setText("D7");

        M1.setText("M1");

        MREQ.setText("MREQ");

        IORQ.setText("IORQ");

        RD.setText("RD");

        WR.setText("WR");

        RFSH.setText("RFSH");

        HALT.setText("HALT");

        WAIT.setText("WAIT");

        INT.setText("INT");

        MMI.setText("MMI");

        RESET.setText("RESET");

        BUSRQ.setText("BUSRQ");

        GND.setText("GND");

        BUSACK.setText("BUSACK");

        V5.setText("+5V");

        CLK.setText("CLK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(M1)
                    .addComponent(MREQ)
                    .addComponent(IORQ)
                    .addComponent(RD)
                    .addComponent(WR)
                    .addComponent(RFSH)
                    .addComponent(HALT)
                    .addComponent(WAIT)
                    .addComponent(INT)
                    .addComponent(MMI)
                    .addComponent(RESET)
                    .addComponent(BUSRQ)
                    .addComponent(GND)
                    .addComponent(BUSACK)
                    .addComponent(V5)
                    .addComponent(CLK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A0)
                    .addComponent(A1)
                    .addComponent(A2)
                    .addComponent(A3)
                    .addComponent(A4)
                    .addComponent(A5)
                    .addComponent(A6)
                    .addComponent(A7)
                    .addComponent(A8)
                    .addComponent(A9)
                    .addComponent(A10)
                    .addComponent(A11)
                    .addComponent(A12)
                    .addComponent(A13)
                    .addComponent(A14)
                    .addComponent(A15)
                    .addComponent(D0)
                    .addComponent(D1)
                    .addComponent(D2)
                    .addComponent(D3)
                    .addComponent(D4)
                    .addComponent(D5)
                    .addComponent(D6)
                    .addComponent(D7))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(A0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A15)
                        .addGap(18, 18, 18)
                        .addComponent(D0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(M1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MREQ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IORQ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RFSH)
                        .addGap(18, 18, 18)
                        .addComponent(HALT)
                        .addGap(18, 18, 18)
                        .addComponent(WAIT)
                        .addGap(18, 18, 18)
                        .addComponent(INT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MMI)
                        .addGap(18, 18, 18)
                        .addComponent(RESET)
                        .addGap(18, 18, 18)
                        .addComponent(BUSRQ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BUSACK)
                        .addGap(42, 42, 42)
                        .addComponent(CLK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(V5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GND)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
*/
    
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        A0 = new javax.swing.JLabel();
        A1 = new javax.swing.JLabel();
        A2 = new javax.swing.JLabel();
        A3 = new javax.swing.JLabel();
        A4 = new javax.swing.JLabel();
        A5 = new javax.swing.JLabel();
        A6 = new javax.swing.JLabel();
        A7 = new javax.swing.JLabel();
        A8 = new javax.swing.JLabel();
        A9 = new javax.swing.JLabel();
        A10 = new javax.swing.JLabel();
        A11 = new javax.swing.JLabel();
        A12 = new javax.swing.JLabel();
        A13 = new javax.swing.JLabel();
        A14 = new javax.swing.JLabel();
        A15 = new javax.swing.JLabel();
        D0 = new javax.swing.JLabel();
        D1 = new javax.swing.JLabel();
        D2 = new javax.swing.JLabel();
        D3 = new javax.swing.JLabel();
        D4 = new javax.swing.JLabel();
        D5 = new javax.swing.JLabel();
        D6 = new javax.swing.JLabel();
        D7 = new javax.swing.JLabel();
        M1 = new javax.swing.JLabel();
        MREQ = new javax.swing.JLabel();
        IORQ = new javax.swing.JLabel();
        RD = new javax.swing.JLabel();
        WR = new javax.swing.JLabel();
        RFSH = new javax.swing.JLabel();
        HALT = new javax.swing.JLabel();
        WAIT = new javax.swing.JLabel();
        INT = new javax.swing.JLabel();
        MMI = new javax.swing.JLabel();
        RESET = new javax.swing.JLabel();
        BUSRQ = new javax.swing.JLabel();
        GND = new javax.swing.JLabel();
        BUSACK = new javax.swing.JLabel();
        V5 = new javax.swing.JLabel();
        CLK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Z80");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel1)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        A0.setText("A0");
A0.setOpaque(true);
A0.setBackground(Color.white);
A1.setText("A1");
A1.setOpaque(true);
A1.setBackground(Color.white);
A2.setText("A2");
A2.setOpaque(true);
A2.setBackground(Color.white);
A3.setText("A3");
A3.setOpaque(true);
A3.setBackground(Color.white);
A4.setText("A4");
A4.setOpaque(true);
A4.setBackground(Color.white);
A5.setText("A5");
A5.setOpaque(true);
A5.setBackground(Color.white);
A6.setText("A6");
A6.setOpaque(true);
A6.setBackground(Color.white);
A7.setText("A7");
A7.setOpaque(true);
A7.setBackground(Color.white);
A8.setText("A8");
A8.setOpaque(true);
A8.setBackground(Color.white);
A9.setText("A9");
A9.setOpaque(true);
A9.setBackground(Color.white);
A10.setText("A10");
A10.setOpaque(true);
A10.setBackground(Color.white);
A11.setText("A11");
A11.setOpaque(true);
A11.setBackground(Color.white);
A12.setText("A12");
A12.setOpaque(true);
A12.setBackground(Color.white);
A13.setText("A13");
A13.setOpaque(true);
A13.setBackground(Color.white);
A14.setText("A14");
A14.setOpaque(true);
A14.setBackground(Color.white);
A15.setText("A15");
A15.setOpaque(true);
A15.setBackground(Color.white);
D0.setText("D0");
D0.setOpaque(true);
D0.setBackground(Color.white);
D1.setText("D1");
D1.setOpaque(true);
D1.setBackground(Color.white);
D2.setText("D2");
D2.setOpaque(true);
D2.setBackground(Color.white);
D3.setText("D3");
D3.setOpaque(true);
D3.setBackground(Color.white);
D4.setText("D4");
D4.setOpaque(true);
D4.setBackground(Color.white);
D5.setText("D5");
D5.setOpaque(true);
D5.setBackground(Color.white);
D6.setText("D6");
D6.setOpaque(true);
D6.setBackground(Color.white);
D7.setText("D7");
D7.setOpaque(true);
D7.setBackground(Color.white);
M1.setText("M1");
M1.setOpaque(true);
M1.setBackground(Color.white);
MREQ.setText("MREQ");
MREQ.setOpaque(true);
MREQ.setBackground(Color.white);
IORQ.setText("IORQ");
IORQ.setOpaque(true);
IORQ.setBackground(Color.white);
RD.setText("RD");
RD.setOpaque(true);
RD.setBackground(Color.white);
WR.setText("WR");
WR.setOpaque(true);
WR.setBackground(Color.white);
RFSH.setText("RFSH");
RFSH.setOpaque(true);
RFSH.setBackground(Color.white);
HALT.setText("HALT");
HALT.setOpaque(true);
HALT.setBackground(Color.white);
WAIT.setText("WAIT");
WAIT.setOpaque(true);
WAIT.setBackground(Color.white);
INT.setText("INT");
INT.setOpaque(true);
INT.setBackground(Color.white);
MMI.setText("MMI");
MMI.setOpaque(true);
MMI.setBackground(Color.white);
RESET.setText("RESET");
RESET.setOpaque(true);
RESET.setBackground(Color.white);
BUSRQ.setText("BUSRQ");
BUSRQ.setOpaque(true);
BUSRQ.setBackground(Color.white);
GND.setText("GND");
GND.setOpaque(true);
GND.setBackground(Color.GRAY);
BUSACK.setText("BUSACK");
BUSACK.setOpaque(true);
BUSACK.setBackground(Color.white);
V5.setText("+5V");
V5.setOpaque(true);
V5.setBackground(Color.red);
CLK.setText("CLK");
CLK.setOpaque(true);
CLK.setBackground(Color.white);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(M1)
                    .addComponent(MREQ)
                    .addComponent(IORQ)
                    .addComponent(RD)
                    .addComponent(WR)
                    .addComponent(RFSH)
                    .addComponent(HALT)
                    .addComponent(WAIT)
                    .addComponent(INT)
                    .addComponent(MMI)
                    .addComponent(RESET)
                    .addComponent(BUSRQ)
                    .addComponent(GND)
                    .addComponent(BUSACK)
                    .addComponent(V5)
                    .addComponent(CLK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A0)
                    .addComponent(A1)
                    .addComponent(A2)
                    .addComponent(A3)
                    .addComponent(A4)
                    .addComponent(A5)
                    .addComponent(A6)
                    .addComponent(A7)
                    .addComponent(A8)
                    .addComponent(A9)
                    .addComponent(A10)
                    .addComponent(A11)
                    .addComponent(A12)
                    .addComponent(A13)
                    .addComponent(A14)
                    .addComponent(A15)
                    .addComponent(D0)
                    .addComponent(D1)
                    .addComponent(D2)
                    .addComponent(D3)
                    .addComponent(D4)
                    .addComponent(D5)
                    .addComponent(D6)
                    .addComponent(D7))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(A0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A15)
                        .addGap(18, 18, 18)
                        .addComponent(D0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(M1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MREQ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IORQ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RFSH)
                        .addGap(18, 18, 18)
                        .addComponent(HALT)
                        .addGap(18, 18, 18)
                        .addComponent(WAIT)
                        .addGap(18, 18, 18)
                        .addComponent(INT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MMI)
                        .addGap(18, 18, 18)
                        .addComponent(RESET)
                        .addGap(18, 18, 18)
                        .addComponent(BUSRQ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BUSACK)
                        .addGap(42, 42, 42)
                        .addComponent(CLK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(V5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GND)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pastilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pastilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pastilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pastilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pastilla().setVisible(true);
            }
        });
    }
/*
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A0;
    private javax.swing.JLabel A1;
    private javax.swing.JLabel A10;
    private javax.swing.JLabel A11;
    private javax.swing.JLabel A12;
    private javax.swing.JLabel A13;
    private javax.swing.JLabel A14;
    private javax.swing.JLabel A15;
    private javax.swing.JLabel A2;
    private javax.swing.JLabel A3;
    private javax.swing.JLabel A4;
    private javax.swing.JLabel A5;
    private javax.swing.JLabel A6;
    private javax.swing.JLabel A7;
    private javax.swing.JLabel A8;
    private javax.swing.JLabel A9;
    private javax.swing.JLabel BUSACK;
    private javax.swing.JLabel BUSRQ;
    private javax.swing.JLabel CLK;
    private javax.swing.JLabel D0;
    private javax.swing.JLabel D1;
    private javax.swing.JLabel D2;
    private javax.swing.JLabel D3;
    private javax.swing.JLabel D4;
    private javax.swing.JLabel D5;
    private javax.swing.JLabel D6;
    private javax.swing.JLabel D7;
    private javax.swing.JLabel GND;
    private javax.swing.JLabel HALT;
    private javax.swing.JLabel INT;
    private javax.swing.JLabel IORQ;
    private javax.swing.JLabel M1;
    private javax.swing.JLabel MMI;
    private javax.swing.JLabel MREQ;
    private javax.swing.JLabel RD;
    private javax.swing.JLabel RESET;
    private javax.swing.JLabel RFSH;
    private javax.swing.JLabel V5;
    private javax.swing.JLabel WAIT;
    private javax.swing.JLabel WR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
*/
    public javax.swing.JLabel A0;
public javax.swing.JLabel A1;
public javax.swing.JLabel A10;
public javax.swing.JLabel A11;
public javax.swing.JLabel A12;
public javax.swing.JLabel A13;
public javax.swing.JLabel A14;
public javax.swing.JLabel A15;
public javax.swing.JLabel A2;
public javax.swing.JLabel A3;
public javax.swing.JLabel A4;
public javax.swing.JLabel A5;
public javax.swing.JLabel A6;
public javax.swing.JLabel A7;
public javax.swing.JLabel A8;
public javax.swing.JLabel A9;
public javax.swing.JLabel BUSACK;
public javax.swing.JLabel BUSRQ;
public javax.swing.JLabel CLK;
public javax.swing.JLabel D0;
public javax.swing.JLabel D1;
public javax.swing.JLabel D2;
public javax.swing.JLabel D3;
public javax.swing.JLabel D4;
public javax.swing.JLabel D5;
public javax.swing.JLabel D6;
public javax.swing.JLabel D7;
public javax.swing.JLabel GND;
public javax.swing.JLabel HALT;
public javax.swing.JLabel INT;
public javax.swing.JLabel IORQ;
public javax.swing.JLabel M1;
public javax.swing.JLabel MMI;
public javax.swing.JLabel MREQ;
public javax.swing.JLabel RD;
public javax.swing.JLabel RESET;
public javax.swing.JLabel RFSH;
public javax.swing.JLabel V5;
public javax.swing.JLabel WAIT;
public javax.swing.JLabel WR;
public javax.swing.JLabel jLabel1;
public javax.swing.JPanel jPanel1;
}